name: Black

on:
  push:
    paths:
      - '**/*.py'
      - '.github/workflows/black.yml'
  pull_request:
    paths:
      - '**/*.py'
      - '.github/workflows/black.yml'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --diff"
